# Generated by Django 3.1 on 2022-04-05 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shelf', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ('-created_date',)},
        ),
    ]
